apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
  labels:
    name: mongo
  annotations:
    metallb.universe.tf/address-pool: mongodb-pool
spec:
  ports:
    - port: 27017
      targetPort: 27017
  #clusterIP: None
  selector:
    app: mongo
  type: LoadBalancer
