apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: mongodb
  labels:
    name: mongo
  annotations:
    metallb.universe.tf/address-pool: mongodb-pool
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
  type: LoadBalancer 
