apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mongodb-0
spec:
  storageClassName: "mongodb-volume"
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.11
    path: "/volume2/NFS/homelab/mongodb-volume/datadir-mongodb-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mongodb-1
spec:
  storageClassName: "mongodb-volume"
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.11
    path: "/volume2/NFS/homelab/mongodb-volume/datadir-mongodb-1"
