apiVersion: v1
kind: Service
metadata:
  name: instance1-lb-svc
  namespace: mongodb
  annotations:
    metallb.universe.tf/address-pool: mongodb-pool
  labels:
    app: instance1-mongodb-svc
spec:
  ports:
    - name: mongodb
      port: 27018
      protocol: TCP
      targetPort: 27017
  selector:
    app: instance1-mongodb-svc
  type: LoadBalancer
